networks:
  my-network:
    driver: bridge

services:
  database:
    image: pgvector/pgvector:pg18-trixie
    container_name: miraflix_db
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: my_redis
    volumes:
      - ./data:/app/data
    ports:
      - "6379:6379"
    networks:
      - my-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: my_ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - my-network
    restart: unless-stopped
    environment:
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: rq worker --with-scheduler --url redis://redis:6379/0 default
    # container_name: my_worker
    networks:
      - my-network
    depends_on:
      - redis
      - ollama

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    networks:
      - my-network
    restart: unless-stopped
    depends_on:
      - redis
      - ollama
      - database
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  k6:
    image: grafana/k6
    container_name: my_k6
    command: run /scripts/script.js
    volumes:
      - ./k6:/scripts
    networks:
      - my-network
    depends_on:
      redis:
        condition: service_started
      ollama:
        condition: service_started
      backend:
        condition: service_started # service_healthy
