networks:
  my-network:
    driver: bridge

# Define named volumes for persistent data storage
volumes:
  db_data:
services:
  database:
    image: pgvector/pgvector:pg18-trixie
    container_name: miraflix_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # use a named volume to persist the database data
    volumes:
      - db_data:/var/lib/postgresql


    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: my_redis
    volumes:
      - ./data:/app/data
    ports:
      - "6379:6379"
    networks:
      - my-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: my_ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - my-network
    restart: unless-stopped
    environment:
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: "all"
    #           capabilities: [gpu]

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: rq worker --with-scheduler --url redis://redis:6379/0 videos # "videos" is the name of the queue to listen for
    # container_name: my_worker # Removed to allow multiple workers
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - my-network
    depends_on:
      - redis
      - ollama

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    networks:
      - my-network
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
      ollama:
        condition: service_started
      database:
        condition: service_healthy
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      # pure python health check to avoid dependency on curl
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/')"]
      interval: 10s
      timeout: 5s
      retries: 5

  k6:
    image: grafana/k6
    container_name: my_k6
    # Available scenarios: smoke, load, queue, search, stress
    #   docker compose run --rm k6 run -e SCENARIO=load /scripts/script.js
    #   docker compose run --rm k6 run -e SCENARIO=queue /scripts/script.js
    #   docker compose run --rm k6 run -e SCENARIO=search /scripts/script.js
    #   docker compose run --rm k6 run -e SCENARIO=stress /scripts/script.js
    # command: run -e SCENARIO=smoke /scripts/script.js
    volumes:
      - ./k6:/scripts
    networks:
      - my-network
    restart: "no"
    depends_on:
      backend:
        condition: service_started


